apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    packaging.carvel.dev/package: tas-adapter-tap-install
    tkg.tanzu.vmware.com/tanzu-package: tas-adapter-tap-install
  creationTimestamp: "2024-03-20T19:22:18Z"
  name: tas-adapter-tap-install-sa
  namespace: tap-install