apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    packaging.carvel.dev/package: tas-adapter-tap-install
    tkg.tanzu.vmware.com/tanzu-package: tas-adapter-tap-install
  name: tas-adapter-tap-install-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
